# Generated by Django 4.0.3 on 2023-06-08 13:23

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 8, 13, 23, 24, 339074))),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('room_name', models.CharField(default='room', max_length=10)),
                ('room_no', models.IntegerField()),
                ('floor', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 8, 13, 23, 24, 339074))),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('team_name', models.CharField(max_length=250)),
                ('date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(validators=[django.core.validators.MinValueValidator(datetime.time(9, 0)), django.core.validators.MaxValueValidator(datetime.time(18, 0))])),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='hall.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
