# Generated by Django 4.0.3 on 2023-06-14 17:02

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 14, 17, 2, 52, 355376))),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('room_name', models.CharField(default='room', max_length=10)),
                ('room_no', models.IntegerField()),
                ('floor', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=250)),
                ('start_time', models.DateTimeField(default=datetime.datetime(1, 1, 1, 9, 0, tzinfo=utc))),
                ('end_time', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(1, 1, 1, 9, 0, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(1, 1, 1, 18, 0, tzinfo=utc))])),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='hall.room')),
            ],
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(fields=('room', 'start_time'), name='unique_booking'),
        ),
    ]
