# Generated by Django 4.0.3 on 2023-06-14 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0005_alter_meeting_start_time_alter_room_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 17, 30, 16, 691173)),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 14, 17, 30, 16, 691169)),
        ),
    ]
